version: '3.8'

services:  
  web-api:
    depends_on:
      - "redis_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:5269"
    links:
      - "redis_image"

  redis_image:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"