version: '3'
services:
  flight-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5269:5269"
    depends_on:
      - redis
    networks:
      - mynetwork
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork
networks:
  mynetwork:
